export const brazilStates = [
  { label: "Acre", value: "acre", id: "AC" },
  { label: "Alagoas", value: "alagoas", id: "AL" },
  { label: "Amapá", value: "amapá", id: "AP" },
  { label: "Amazonas", value: "amazonas", id: "AM" },
  { label: "Bahia", value: "bahia", id: "BA" },
  { label: "Ceará", value: "ceará", id: "CE" },
  { label: "Distrito Federal", value: "distrito federal", id: "DF" },
  { label: "Espírito Santo", value: "espírito santo", id: "ES" },
  { label: "Goiás", value: "goiás", id: "GO" },
  { label: "Maranhão", value: "maranhão", id: "MA" },
  { label: "Mato Grosso", value: "mato grosso", id: "MT" },
  { label: "Mato Grosso do Sul", value: "mato grosso do sul", id: "MS" },
  { label: "Minas Gerais", value: "minas gerais", id: "MG" },
  { label: "Pará", value: "pará", id: "PA" },
  { label: "Paraíba", value: "paraíba", id: "PB" },
  { label: "Paraná", value: "paraná", id: "PR" },
  { label: "Pernambuco", value: "pernambuco", id: "PE" },
  { label: "Piauí", value: "piuí", id: "PI" },
  { label: "Rio de Janeiro", value: "rio de janeiro", id: "RJ" },
  { label: "Rio Grande do Norte", value: "rio grande do norte", id: "RN" },
  { label: "Rio Grande do Sul", value: "rio grande do sul", id: "RS" },
  { label: "Rondônia", value: "rondônia", id: "RO" },
  { label: "Roraima", value: "roraima", id: "RR" },
  { label: "Santa Catarina", value: "santa catarina", id: "SC" },
  { label: "São Paulo", value: "são paulo", id: "SP" },
  { label: "Sergipe", value: "sergipe", id: "SE" },
  { label: "Tocantins", value: "tocantins", id: "TO" }
];
